# the name of the current app
spring:
  application:
    name: spring-boot-yaml-usage-demo

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration

# logging settings
logging:
  level:
    root: info
    org:
      springframework: warn

  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'

# defining a custom property
connection:
  timeout: 5000